name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run pylint
      run: pylint app
    - name: Ensure that the application runs without failing.
      run: python3 -m app
